# -*- coding: utf-8 -*-
"""notebook-filippa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10jizq6PfMbWMjML0HbVMGTTVsMobYjvF
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#pipelines
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer, make_column_selector, make_column_transformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, RobustScaler
from sklearn.impute import SimpleImputer

#fitting
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate

from sklearn.decomposition import PCA

df = pd.read_csv('complete_dataset.csv')

df.head()

df.info()

df.describe()

df.isna().sum()

df.duplicated().sum()

df.hist(column='RRP', bins=20, grid=True)

df['RRP'][df['RRP'] < 500].hist(bins=50)
plt.show()

plt.figure(figsize=(8,4))
plt.boxplot(df['RRP'], vert=False)
plt.title("Boxplot of RRP")
plt.xlabel("RRP")
plt.show()

"""#TO Datetime"""

df['date'] = pd.to_datetime(df['date'])

df.set_index('date', inplace=True)

df['holiday'].unique()

df['holiday'] = df['holiday'].map({'Y': 1, 'N': 0})

df['school_day'].unique()

df['school_day'] = df['school_day'].map({'Y': 1, 'N': 0})

df.head()

corr = df.corr()

plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", cbar=True)
plt.title("Correlation Matrix Heatmap")
plt.show()

df.info()

df.columns

df[['rainfall']].boxplot()

df[['solar_exposure']].boxplot()

df[['max_temperature']].boxplot()

"""### Pipeline"""

num_transformer = make_pipeline(SimpleImputer(strategy='median'), RobustScaler())

cat_transformer = OneHotEncoder()

num_col = make_column_selector(dtype_include=['float64', 'int64'])
cat_col = make_column_selector(dtype_include='object')

preproc = make_column_transformer(
    (num_transformer, num_col),
    (cat_transformer, cat_col)
)

preproc

df.columns

X = df.drop(columns=["RRP",'demand_pos_RRP', 'RRP_positive', 'demand_neg_RRP', 'frac_at_neg_RRP'])
y = df["RRP"]

X_preproc = preproc.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_preproc, y, test_size=0.3, random_state=42)

model = LinearRegression()

model.fit(X_train, y_train)

model.score(X_test, y_test)

cv_results = cross_validate(model, X_preproc, y, cv=5)

cv_results

import pandas as pd
from statsmodels.tsa.arima.model import ARIMA
import matplotlib.pyplot as plt               # Daten laden
df = pd.read_csv("complete_dataset.csv")
df['date'] = pd.to_datetime(df['date'])
df = df.set_index('date')       # Nur Preis-Spalte
series = df['RRP'] # ARIMA Modell trainieren (z. B. (p=5, d=1, q=0))
model = ARIMA(series, order=(5,1,0))
model_fit = model.fit() # Prognose der nächsten 7 Tage
forecast = model_fit.forecast(steps=7)
print(forecast)
plt.figure(figsize=(12,5))
plt.plot(series[-100:], label='Historisch')
plt.plot(forecast, label='Forecast', color='red')
plt.legend()
plt.show()


import pandas as pd
from pmdarima import auto_arima
from statsmodels.tsa.statespace.sarimax import SARIMAX
import matplotlib.pyplot as plt          # Load dataset
df = pd.read_csv("complete_dataset.csv")
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date').set_index('date')# Univariate time series
series = df['RRP'] #  choose exogenous variables
exog_vars = df[['demand', 'min_temperature', 'max_temperature', 'solar_exposure']]
auto_model = auto_arima(
    series,
    exogenous=exog_vars,      # None if just univariate
    seasonal=True,             # Include seasonality
    m=7,                       # Weekly seasonality
    trace=True,
    error_action='ignore',
    suppress_warnings=True,
    stepwise=True
)
print("Best ARIMA order:", auto_model.order)

print("Best seasonal order:", auto_model.seasonal_order)







from statsmodels.tsa.statespace.sarimax import SARIMAX
import numpy as np    # Exogene Features auswählen
exog_vars = df[['demand', 'min_temperature', 'max_temperature', 'solar_exposure']]
# Sicherstellen, dass keine NaNs oder Infs drin sind
exog_vars = exog_vars.replace([np.inf, -np.inf], np.nan)  # Inf → NaN
exog_vars = exog_vars.fillna(method='ffill')              # Fehlende Werte auffüllen (Forward Fill)
exog_vars = exog_vars.fillna(method='bfill')              # Falls am Anfang noch NaN → Backward Fill
train_size = int(len(df) * 0.8)
train_series = df['RRP'][:train_size]
test_series = df['RRP'][train_size:]
train_exog = exog_vars[:train_size]
test_exog = exog_vars[train_size:]  # Fit SARIMAX with exogenous variables
sarimax_model = SARIMAX(
    train_series,
    order=(1,1,1),
    seasonal_order=(0,0,0,7),
    exog=train_exog
)
sarimax_fit = sarimax_model.fit(disp=False)
print(sarimax_fit.summary())   # Forecast
forecast = sarimax_fit.predict(start=test_series.index[0], end=test_series.index[-1], exog=test_exog)    # Plot
import matplotlib.pyplot as plt
plt.figure(figsize=(12,5))
plt.plot(train_series[-100:], label='Train')
plt.plot(test_series, label='Test')
plt.plot(forecast, label='Forecast', color='red')
plt.legend()
plt.title("SARIMAX Forecast with Exogenous Variables")
plt.show()  #SARIMAX Forecast auf Testdaten machen
pred = sarimax_fit.get_forecast(steps=len(test_series), exog=test_exog)
pred_mean = pred.predicted_mean
# Metrik berechnen
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
mae_sarimax = mean_absolute_error(test_series, pred_mean)
rmse_sarimax = np.sqrt(mean_squared_error(test_series, pred_mean))
r2_sarimax = r2_score(test_series, pred_mean)
print(f"SARIMAX → MAE={mae_sarimax:.2f}, RMSE={rmse_sarimax:.2f}, R²={r2_sarimax:.2f}")
# vergleich mit baseline
print("Naïve baseline: MAE=24.60, RMSE=156.26, R²=-0.44")
print(f"SARIMAX      : MAE={mae_sarimax:.2f}, RMSE={rmse_sarimax:.2f}, R²={r2_sarimax:.2f}")

import pandas as pd
import numpy as np
from darts import TimeSeries
from darts.models import LinearRegressionModel
from darts.metrics import mae, rmse, r2_score
# 1. Load data
df = pd.read_csv("/Users/Alessio/Desktop/complete_dataset.csv")
df['date'] = pd.to_datetime(df['date'])
series = TimeSeries.from_dataframe(df, 'date', 'RRP')
# 2. Feature Engineering
# Make sure to handle all non-numeric conversions FIRST.
# Convert school_day and holiday to 0/1
df['school_day'] = df['school_day'].map({'Y': 1, 'N': 0})
df['holiday'] = df['holiday'].map({'Y': 1, 'N': 0})
# Calendar features
df['dayofweek'] = df['date'].dt.dayofweek
df['month'] = df['date'].dt.month
df['weekofyear'] = df['date'].dt.isocalendar().week.astype(int)
df['is_weekend'] = (df['dayofweek'] >= 5).astype(int)
# Lag features (1, 7, 14 days back)
for lag in [1, 7, 14]:
    df[f'lag_{lag}'] = df['RRP'].shift(lag)
# Rolling means
df['rolling_mean_7'] = df['RRP'].rolling(7).mean()
df['rolling_mean_30'] = df['RRP'].rolling(30).mean()
# Interaction features
df['temp_range'] = df['max_temperature'] - df['min_temperature']
df['rain_x_temp'] = df['rainfall'] * df['max_temperature']
# 3. Handle NaNs (from lags/rollings)
# This step is critical and must be done after all feature creation.
df = df.fillna(method="bfill").fillna(method="ffill")
# 4. Build covariates TimeSeries
feature_cols = [
    'min_temperature', 'max_temperature', 'solar_exposure', 'rainfall',
    'school_day', 'holiday',
    'dayofweek', 'month', 'weekofyear', 'is_weekend',
    'lag_1', 'lag_7', 'lag_14',
    'rolling_mean_7', 'rolling_mean_30',
    'temp_range', 'rain_x_temp'
]
# Ensure all columns are numeric
for col in feature_cols:
    # Use to_numeric with 'coerce' to handle any unexpected non-numeric values
    # and then fill any NaNs created.
    df[col] = pd.to_numeric(df[col], errors='coerce')
# Fill any NaNs that might have been introduced
df = df.fillna(method="bfill").fillna(method="ffill")
# Now build covariates TimeSeries
covariates_ts = TimeSeries.from_dataframe(df, 'date', feature_cols)
# Extend covariates horizon
from darts.utils.timeseries_generation import datetime_attribute_timeseries
# Fill 7 extra days by repeating last values
extra_days = pd.date_range(df['date'].max() + pd.Timedelta(days=1),
  periods=7, freq="D")
extra_cov = pd.DataFrame(index=extra_days)
for col in feature_cols:
    extra_cov[col] = df[col].iloc[-1]  # repeat last value
extra_cov = extra_cov.reset_index().rename(columns={'index': 'date'})
df_extended = pd.concat([df, extra_cov], ignore_index=True)
# Rebuild covariates TimeSeries
covariates_ts = TimeSeries.from_dataframe(df_extended, 'date', feature_cols)
# Retrain/test split with extended covariates
train, test = series[:-30], series[-30:]
# Covariates for training
cov_train = covariates_ts[:-30]
# Covariates for prediction (test) must include the look-ahead window
# The max lag is 7, so we need the last 30 (for test) + 7 days
cov_test = covariates_ts[-37:]
# train model with covariants
model = LinearRegressionModel(
    lags=[-1, -2, -7],
    lags_future_covariates=[0, 1, 7]
)
model.fit(train, future_covariates=cov_train)
# forecast
pred = model.predict(len(test), future_covariates=cov_test)
# evaluate
mae_val = mae(test, pred)
rmse_val = rmse(test, pred)
r2_val = r2_score(test, pred)
print(f"LinearRegressionModel + Features  MAE={mae_val:.2f}, RMSE={rmse_val:.2f}, R²={r2_val:.3f}")

from darts import TimeSeries
from darts.models import LinearRegressionModel
from darts.metrics import mae, rmse, r2_score
import pandas as pd
# Carica dati
df = pd.read_csv("../raw_data/complete_dataset.csv")
df['date'] = pd.to_datetime(df['date'])
series = TimeSeries.from_dataframe(df, 'date', 'RRP')
# Split train/test
train = series[:-30]  # Tutti tranne ultimi 30
test = series[-30:]   # Ultimi 30 per test
# Modello
model = LinearRegressionModel(lags=7)
model.fit(train)
pred = model.predict(30)
# Metriche
mae_val = mae(test, pred)
rmse_val = rmse(test, pred)
r2_val = r2_score(test, pred)
print(f"MAE:  {mae_val:.2f}")
print(f"RMSE: {rmse_val:.2f}")
print(f"R²:   {r2_val:.3f}")

import pandas as pd
import matplotlib.pyplot as plt

import numpy as np
from darts import TimeSeries
from darts.models import LinearRegressionModel
from darts.metrics import mae, rmse, r2_score
# 1. Load data
df = pd.read_csv("/Users/Alessio/Desktop/complete_dataset.csv")
df['date'] = pd.to_datetime(df['date'])
df.head()
series = TimeSeries.from_dataframe(df, 'date', 'RRP')
plt.figure(figsize=(12,5))
plt.plot(df['date'], df['RRP'], label="RRP")
plt.title("RRP Zeitreihe (Rohdaten)")
plt.xlabel("Datum")
plt.ylabel("RRP")
plt.legend()
plt.show()
# 2. Feature Engineering
# Make sure to handle all non-numeric conversions FIRST.
# Convert school_day and holiday to 0/1
df['school_day'] = df['school_day'].map({'Y': 1, 'N': 0})
df['holiday'] = df['holiday'].map({'Y': 1, 'N': 0})
# Calendar features
df['dayofweek'] = df['date'].dt.dayofweek
df['month'] = df['date'].dt.month
df['weekofyear'] = df['date'].dt.isocalendar().week.astype(int)
df['is_weekend'] = (df['dayofweek'] >= 5).astype(int)
# Lag features (1, 7, 14 days back)
for lag in [1, 7, 14]:
    df[f'lag_{lag}'] = df['RRP'].shift(lag)
# Rolling means
df['rolling_mean_7'] = df['RRP'].rolling(7).mean()
df['rolling_mean_30'] = df['RRP'].rolling(30).mean()
# Interaction features
df['temp_range'] = df['max_temperature'] - df['min_temperature']
df['rain_x_temp'] = df['rainfall'] * df['max_temperature']
# 3. Handle NaNs (from lags/rollings)
# This step is critical and must be done after all feature creation.
df = df.fillna(method="bfill").fillna(method="ffill")
fig, ax = plt.subplots(2, 1, figsize=(12,8), sharex=True)
ax[0].plot(df['date'], df['RRP'], label="RRP")
ax[0].plot(df['date'], df['lag_7'], label="Lag 7")
ax[0].set_title("Lag Feature Beispiel")
ax[0].legend()
ax[1].plot(df['date'], df['RRP'], label="RRP")
ax[1].plot(df['date'], df['rolling_mean_30'], label="Rolling Mean 30d")
ax[1].set_title("Rolling Feature Beispiel")
ax[1].legend()
plt.show()
# 4. Build covariates TimeSeries
feature_cols = [
    'min_temperature', 'max_temperature', 'solar_exposure', 'rainfall',
    'school_day', 'holiday',
    'dayofweek', 'month', 'weekofyear', 'is_weekend',
    'lag_1', 'lag_7', 'lag_14',
    'rolling_mean_7', 'rolling_mean_30',
    'temp_range', 'rain_x_temp'
]
# Ensure all columns are numeric
for col in feature_cols:
    # Use to_numeric with 'coerce' to handle any unexpected non-numeric values
    # and then fill any NaNs created.
    df[col] = pd.to_numeric(df[col], errors='coerce')
# Fill any NaNs that might have been introduced
df = df.fillna(method="bfill").fillna(method="ffill")
# Now build covariates TimeSeries
covariates_ts = TimeSeries.from_dataframe(df, 'date', feature_cols)
series = TimeSeries.from_dataframe(df, 'date', 'RRP')
df[['date', 'max_temperature', 'rainfall', 'school_day']].set_index('date').plot(
    subplots=True, figsize=(12,6), title=["Max Temp", "Rainfall", "School Day"]
)
plt.show()
# Extend covariates horizon
from darts.utils.timeseries_generation import datetime_attribute_timeseries
# Fill 7 extra days by repeating last values
extra_days = pd.date_range(df['date'].max() + pd.Timedelta(days=1),
  periods=7, freq="D")
extra_cov = pd.DataFrame(index=extra_days)
for col in feature_cols:
    extra_cov[col] = df[col].iloc[-1]  # repeat last value
extra_cov = extra_cov.reset_index().rename(columns={'index': 'date'})
df_extended = pd.concat([df, extra_cov], ignore_index=True)
# Rebuild covariates TimeSeries
covariates_ts = TimeSeries.from_dataframe(df_extended, 'date', feature_cols)
# Retrain/test split with extended covariates
train, test = series[:-300], series[-300:]
# Covariates for training
cov_train = covariates_ts[:-300]
# Covariates for prediction (test) must include the look-ahead window
# The max lag is 7, so we need the last 30 (for test) + 7 days
cov_test = covariates_ts[-307:]
plt.figure(figsize=(12,5))
train.plot(label="Train")
test.plot(label="Test")
plt.title("Train/Test Split")
plt.legend()
plt.show()
# train model with covariants
model = LinearRegressionModel(
    lags=[-1, -2, -7],
    lags_future_covariates=[0, 1, 7]
)
model.fit(train, future_covariates=cov_train)
# forecast
pred = model.predict(len(test), future_covariates=cov_test)
plt.figure(figsize=(12,5))
train.plot(label="Train")
test.plot(label="Test (True)")
pred.plot(label="Forecast")
plt.title("Vorhersage mit LinearRegressionModel")
plt.legend()
plt.show()
# evaluate
mae_val = mae(test, pred)
rmse_val = rmse(test, pred)
r2_val = r2_score(test, pred)
print(f"LinearRegressionModel + Features  MAE={mae_val:.2f}, RMSE={rmse_val:.2f}, R²={r2_val:.3f}")

from darts.models import AutoARIMA

# AutoARIMA sceglie automaticamente (p,d,q)
auto_arima = AutoARIMA(
    start_p=1, start_q=1,
    max_p=7, max_q=7,
    d=None,           # scelto automaticamente
    seasonal=False,   # se vuoi anche stagionalità → True
    stepwise=True
)
auto_arima.fit(train)
pred_autoarima = auto_arima.predict(len(test))

print("AutoARIMA MAE:", mae(test, pred_autoarima))

from darts.models import RegressionModel
from sklearn.ensemble import RandomForestRegressor

rf_model = RegressionModel(
    model=RandomForestRegressor(n_estimators=200, random_state=42),
    lags=[-1, -2, -7],
    lags_future_covariates=[0, 1, 7]
)
rf_model.fit(train, future_covariates=cov_train)
pred_rf = rf_model.predict(len(test), future_covariates=cov_test)

print("RandomForest MAE:", mae(test, pred_rf))

from xgboost import XGBRegressor

xgb_model = RegressionModel(
    model=XGBRegressor(n_estimators=300, max_depth=5, learning_rate=0.05, random_state=42),
    lags=[-1, -2, -7],
    lags_future_covariates=[0, 1, 7]
)
xgb_model.fit(train, future_covariates=cov_train)
pred_xgb = xgb_model.predict(len(test), future_covariates=cov_test)

print("XGBoost MAE:", mae(test, pred_xgb))

plt.figure(figsize=(12,5))
test.plot(label="True")
pred.plot(label="LinearRegression")
pred_autoarima.plot(label="AUTOARIMA")
pred_rf.plot(label="RandomForest")
pred_xgb.plot(label="XGBoost")
plt.title("Forecast Model Comparison")
plt.legend()
plt.show()

from xgboost import XGBRegressor
from darts.models import SKLearnModel
from darts.metrics import mae
import pandas as pd

# XGBoost ottimizzato
xgb_opt = SKLearnModel(
    model=XGBRegressor(n_estimators=500, max_depth=7, learning_rate=0.03,
                      subsample=0.85, gamma=0.1, random_state=42),
    lags=[-1, -2, -7, -14],
    lags_future_covariates=[0, 1, 7]
)

xgb_opt.fit(train, future_covariates=cov_train)

# Calculate required future covariates length
max_future_lag = max(xgb_opt.lags_future_covariates)  # This should be 7
required_cov_length = len(test) + max_future_lag

print(f"Required future covariates length: {required_cov_length}")
print(f"Available cov_test length: {len(cov_test)}")

# Check if we have enough future covariates
if len(cov_test) < required_cov_length:
    print(f"Warning: cov_test is too short. Need {required_cov_length} steps, but only have {len(cov_test)}")

    # Option 1: Use a shorter prediction horizon if possible
    if len(test) > (len(cov_test) - max_future_lag):
        shorter_horizon = len(cov_test) - max_future_lag
        print(f"Using shorter prediction horizon: {shorter_horizon} instead of {len(test)}")
        pred_opt = xgb_opt.predict(shorter_horizon, future_covariates=cov_test)

        # Compare only the available part of test
        test_subset = test[:shorter_horizon]
        print("XGBoost Ottimizzato MAE:", mae(test_subset, pred_opt))
    else:
        # Option 2: If you can extend cov_test, do it here
        # For now, we'll proceed with available data (may cause error)
        pred_opt = xgb_opt.predict(len(test), future_covariates=cov_test)
        print("XGBoost Ottimizzato MAE:", mae(test, pred_opt))
else:
    # We have enough data, proceed normally
    pred_opt = xgb_opt.predict(len(test), future_covariates=cov_test)
    print("XGBoost Ottimizzato MAE:", mae(test, pred_opt))

from xgboost import XGBRegressor
from darts.models import SKLearnModel
from darts.metrics import mae
import numpy as np

# XGBoost ottimizzato
xgb_opt = SKLearnModel(
    model=XGBRegressor(n_estimators=500, max_depth=7, learning_rate=0.03,
                      subsample=0.85, gamma=0.1, random_state=42),
    lags=[-1, -2, -7, -14],
    lags_future_covariates=[0, 1, 7]
)

xgb_opt.fit(train, future_covariates=cov_train)

# Safe prediction function that handles insufficient covariates
def safe_predict(model, n, future_covariates, test_series):
    # Get the maximum future lag from the model configuration
    # For SKLearnModel, we need to access the internal lags configuration
    max_future_lag = max(model.lags_future_covariates) if hasattr(model, 'lags_future_covariates') else 0

    # If we can't access it directly, assume the maximum from the known configuration
    if max_future_lag == 0:
        max_future_lag = 7  # Based on your [0, 1, 7] configuration

    available_length = len(future_covariates)

    print(f"Max future lag: {max_future_lag}")
    print(f"Available covariates length: {available_length}")
    print(f"Prediction horizon: {n}")

    if available_length >= n + max_future_lag:
        # Enough data for full prediction
        pred = model.predict(n, future_covariates=future_covariates)
        return pred, test_series

    else:
        # Predict only what we can
        possible_n = available_length - max_future_lag
        if possible_n <= 0:
            raise ValueError(f"Not enough future covariates. Need at least {max_future_lag + 1} steps, but only have {available_length}")

        print(f"Warning: Can only predict {possible_n} steps instead of {n}")

        pred = model.predict(possible_n, future_covariates=future_covariates)
        test_subset = test_series[:possible_n]
        return pred, test_subset

# Use the safe prediction function
try:
    pred_opt, test_for_eval = safe_predict(xgb_opt, len(test), cov_test, test)
    print("XGBoost Ottimizzato MAE:", mae(test_for_eval, pred_opt))
except Exception as e:
    print(f"Error during prediction: {e}")

    # Fallback: try without future covariates
    print("Trying without future covariates...")
    xgb_no_cov = SKLearnModel(
        model=XGBRegressor(n_estimators=500, max_depth=7, learning_rate=0.03,
                          subsample=0.85, gamma=0.1, random_state=42),
        lags=[-1, -2, -7, -14]
    )
    xgb_no_cov.fit(train)
    pred_no_cov = xgb_no_cov.predict(len(test))
    print("XGBoost (no covariates) MAE:", mae(test, pred_no_cov))



