# -*- coding: utf-8 -*-
"""notebook-filippa (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UMlNQXz_OuXO8NxbXi6Ycyowijj4gZ6R
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#pipelines
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer, make_column_selector, make_column_transformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, RobustScaler
from sklearn.impute import SimpleImputer

#fitting
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate

from sklearn.decomposition import PCA

df = pd.read_csv('complete_dataset (1).csv')

df.head()

df.info()

df.describe()

df.isna().sum()

df.duplicated().sum()

df.hist(column='RRP', bins=20, grid=True)

df['RRP'][df['RRP'] < 500].hist(bins=50)
plt.show()

plt.figure(figsize=(8,4))
plt.boxplot(df['RRP'], vert=False)
plt.title("Boxplot of RRP")
plt.xlabel("RRP")
plt.show()

"""#TO Datetime"""

df['date'] = pd.to_datetime(df['date'])

df.set_index('date', inplace=True)

df['holiday'].unique()

df['holiday'] = df['holiday'].map({'Y': 1, 'N': 0})

df['school_day'].unique()

df['school_day'] = df['school_day'].map({'Y': 1, 'N': 0})

df.head()

corr = df.corr()

plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", cbar=True)
plt.title("Correlation Matrix Heatmap")
plt.show()

df.info()

df.columns

df[['rainfall']].boxplot()

df[['solar_exposure']].boxplot()

df[['max_temperature']].boxplot()

"""### Pipeline"""

num_transformer = make_pipeline(SimpleImputer(strategy='median'), RobustScaler())

cat_transformer = OneHotEncoder()

num_col = make_column_selector(dtype_include=['float64', 'int64'])
cat_col = make_column_selector(dtype_include='object')

preproc = make_column_transformer(
    (num_transformer, num_col),
    (cat_transformer, cat_col)
)

preproc

df.columns

X = df.drop(columns=["RRP"])
y = df["RRP"]

X_preproc = preproc.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_preproc, y, test_size=0.3, random_state=42)

model = LinearRegression()

model.fit(X_train, y_train)

model.score(X_test, y_test)

cv_results = cross_validate(model, X_preproc, y, cv=5)

cv_results

len(df.columns)

pca = PCA(n_components=12)

num_transformer_standard = make_pipeline(SimpleImputer(strategy='median'), StandardScaler())

preproc_standard = make_column_transformer(
    (num_transformer_standard, num_col),
    (cat_transformer, cat_col),

)

X_standard_preproc = preproc_standard.fit_transform(X)

pca.fit(X_standard_preproc)

W = pca.components_

len(W)

W = pd.DataFrame(W.T, columns=[f'PC{i}' for i in range(1,(len(W)+1))])

X_proj = pca.transform(X_standard_preproc)
X_proj = pd.DataFrame(X_proj, columns=[f'PC{i}' for i in range(1,13)])
X_proj

sns.heatmap(X_proj.corr(), cmap='coolwarm')

model2 = LinearRegression()

cv_results = cross_validate(model2, X_proj, y, cv=5)

cv_results

cv_results['test_score'].mean()

